const car = [
    {
        // id: 1,
        name: "AUDI | A1 | SPORTBACK 30 TFSI S-LINE 1",
        picture: "https://webfiles.movingcar.lu/annonces/1200x900/53188-dlTXSoYqsnthVjFPwkfg.jpg",
        power: 81,
        horses: 110,
        kms: 11400,
        first_registration: "03-2023",
        seating_places: 5,
        doors: 5,
        co2: 125,
        price: 24980,
        fuel_id: 1,
        ext_color_id: 2,
        // int_color: "Noir",
        // transmission: "Manuelle",
        // brand: "Audi",
        // model: "A1",
        // state: 'Occasion',
        // chassis: "test",
        // equipment: "test", 
        created: new Date()
    },
    {
        // id: 2,
        name: "AUDI | A1 | SPORTBACK 30 TFSI S-LINE 2",
        picture: "https://webfiles.movingcar.lu/annonces/1200x900/53188-dlTXSoYqsnthVjFPwkfg.jpg",
        power: 81,
        horses: 110,
        kms: 11400,
        first_registration: "03-2023",
        seating_places: 5,
        doors: 5,
        co2: 125,
        price: 24980,
        fuel_id: 1,
        ext_color_id: 1,
        // int_color: "Noir",
        // transmission: "Manuelle",
        // brand: "Audi",
        // model: "A1",
        // state: 'Occasion',
        // chassis: "test",
        // equipment: "test",
        created: new Date()
    },
    {
        // id: 3,
        name: "AUDI | A1 | SPORTBACK 30 TFSI S-LINE 3",
        picture: "https://webfiles.movingcar.lu/annonces/1200x900/53188-dlTXSoYqsnthVjFPwkfg.jpg",
        power: 81,
        horses: 110,
        kms: 11400,
        first_registration: "03-2023",
        seating_places: 5,
        doors: 5,
        co2: 125,
        price: 24980,
        fuel_id: 1,
        ext_color_id: 1,
        // int_color: "Noir",
        // transmission: "Manuelle",
        // brand: "Audi",
        // model: "A1",
        // state: 'Occasion',
        // chassis: "test",
        // equipment: "test",
        created: new Date()
    },
    {
        // id: 4,
        name: "AUDI | A1 | SPORTBACK 30 TFSI S-LINE 4",
        picture: "https://webfiles.movingcar.lu/annonces/1200x900/53188-dlTXSoYqsnthVjFPwkfg.jpg",
        power: 81,
        horses: 110,
        kms: 11400,
        first_registration: "03-2023",
        seating_places: 5,
        doors: 5,
        co2: 125,
        price: 24980,
        fuel_id: 1,
        ext_color_id: 2,
        // int_color: "Noir",
        // transmission: "Manuelle",
        // brand: "Audi",
        // model: "A1",
        // state: 'Occasion',
        // chassis: "test",
        // equipment: "test",
        created: new Date()
    },
    {
        // id: 5,
        name: "AUDI | A1 | SPORTBACK 30 TFSI S-LINE 5",
        picture: "https://webfiles.movingcar.lu/annonces/1200x900/53188-dlTXSoYqsnthVjFPwkfg.jpg",
        power: 81,
        horses: 110,
        kms: 11400,
        first_registration: "03-2023",
        seating_places: 5,
        doors: 5,
        co2: 125,
        price: 24980,
        fuel_id: 1,
        ext_color_id: 1,
        // int_color: "Noir",
        // transmission: "Manuelle",
        // brand: "Audi",
        // model: "A1",
        // state: 'Occasion',
        // chassis: "test",
        // equipment: "test",
        created: new Date()
    },
   
   ]
   
   module.exports = car;